name: tectalic
favicon: null
layout_spectrum: 1
typography_spectrum: 0.2429
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: The Tectalic
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3A424B'
    - '#FF9A88'
    - '#9BF2FF'
    - '#27BDFF'
    - '#0664B4'
  brandStrength: 0.6740065
  lightness: 0.9433224
  saturation: 0.3979845
  rhythmicContrast: 0.1494408
purpose: []
